# This is a basic workflow to help you get started with Actions

name: Algo 2 SRT 2022-2023

# Controls when the workflow will run
on:
UADB of BAMBEY,Diourbel,SEN
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
Aim:
Dans le but d''aider les futures générations à mieux apréhender la nation dalgo.
  # This workflow contains a single job called "build"
  IDE:
   Codé en Pascal , 
    # The type of runner that the job will run on
    runs-on: All O.S

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
